# .travis.yml

language: node_js
sudo: false
node_js:
  - 10.15.1
script:
  - git config --global user.email "953958160@qq.com"
  - git config --global user.name "fuyz"
  - bash scripts/deploy-to-gh-pages.sh
